version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8009:8009"
    env_file:
      - .env
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8009 --reload
    volumes:
      - .:/app

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-library_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
